ALTER TABLE "Wallet" ADD COLUMN "moneyRub" DOUBLE PRECISION NOT NULL DEFAULT 0, ADD COLUMN "bonusRub" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "TopupRequest" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'KZT';
ALTER TABLE "PayoutRequest" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'KZT';
ALTER TABLE "WalletTransaction" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'KZT';
