ALTER TABLE "DriverProfile" ADD COLUMN IF NOT EXISTS "acceptCityFixed" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "DriverProfile" ADD COLUMN IF NOT EXISTS "acceptCityAuction" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "DriverProfile" ADD COLUMN IF NOT EXISTS "acceptIntercity" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "DriverProfile" ADD COLUMN IF NOT EXISTS "acceptDelivery" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "DriverProfile" ADD COLUMN IF NOT EXISTS "acceptCargo" BOOLEAN NOT NULL DEFAULT true;
